[project]
name = "assignment1-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pip>=26.2.1",
    "spacy>=3.8.16",
]

[project.scripts]
assignment1-genai = "assignment1_genai:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
